<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8QC2CD5" failures="1" tests="7" name="com.test.classes.MyTestClass" time="33.153" errors="0" timestamp="18 Aug 2022 10:27:51 GMT" skipped="4">
  <testcase classname="com.test.classes.MyTestClass" name="getMovieReleaseDateFromIMDB" time="18.451"/>
  <testcase classname="com.test.classes.MyTestClass" name="getMovieReleaseDateFromWikipedia" time="6.778"/>
  <testcase classname="com.test.classes.MyTestClass" name="assertExtractedDetails" time="1.501">
    <skipped/>
  </testcase> <!-- assertExtractedDetails -->
  <testcase classname="com.test.classes.MyTestClass" name="assertExtractedDetails" time="1.768">
    <failure message="expected [17 December 2021] but found [January 7, 2022 (United States)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [January 7, 2022 (United States)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.classes.MyTestClass.assertExtractedDetails(MyTestClass.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- assertExtractedDetails -->
  <testcase classname="com.test.classes.MyTestClass" name="assertExtractedDetails" time="1.604">
    <skipped/>
  </testcase> <!-- assertExtractedDetails -->
  <testcase classname="com.test.classes.MyTestClass" name="assertExtractedDetails" time="1.554">
    <skipped/>
  </testcase> <!-- assertExtractedDetails -->
  <testcase classname="com.test.classes.MyTestClass" name="assertExtractedDetails" time="1.497">
    <skipped/>
  </testcase> <!-- assertExtractedDetails -->
</testsuite> <!-- com.test.classes.MyTestClass -->
